services:
  - type: web
    name: wnba-stats
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    region: oregon
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WNBA_SEASON
        value: "2026"
    healthCheckPath: /health
